### ISSUE TITLE
Learning Blender for our Project Needs

### ISSUE THREAD

**Issue by MErenB** [TeamWombat2023/Bil496-Bitirme-Projesi#11]
Epic: #7 
3D Design with Blender will be learned for designing assets for our games. 

- [x] 3D design basics will be learned. 
- [x] Material (skin for 3D objects) design will be learned.
- [x] A simple game asset (tree, chair etc.) will be created.

The expectations for Blender game asset design:
- Designed objects should match our game style.
- Object materials must conform with the real life light physics. 

This task will be completed when a game asset is created with Blender.
ETA: 2 weeks

**Comment by cagdasgerede** [comment]
Tüm taskların içerikleri ve beklentiler tanımlanmalı. Ne zaman DONE yapılmış sayılacak tariflenmeli. Görev tanımı açık olmalı. ETA belirtilmeli.

**Comment by MErenB** [comment]
Blender 3D design tool is learned. Some simple 3D objects are designed with it. The images of the created objects can be shown below.



![Image](https://user-images.githubusercontent.com/78208804/216848412-e00cbb3b-c3cc-4a82-a91e-c1e2e755a166.png)

Image 1: A baseball bat for entertainment in the game's lobby. 



![Image](https://user-images.githubusercontent.com/78208804/216848447-a7c5406d-8c7e-4c41-9eb4-bf8117afc99d.png)

Image 2: A table for placing the interactable items.


![Image](https://user-images.githubusercontent.com/78208804/216848516-452b494f-68f2-4cd4-8a30-f5aa10e966f4.png)
Image 3:  3D Interactable button for starting the game in the lobby.


From now on, the required objects for our games can be designed by our team. The game requirements will be created mainly by us.
