### ISSUE TITLE
Design of the Lobby

### ISSUE THREAD

**Issue by okg21** [TeamWombat2023/Bil496-Bitirme-Projesi#18]
Epic: #10 
A lobby should be designed such that:
- [ ] Players can start the game when all are ready.
- [ ] Players can interact with the objects.
- [ ] Players can interact with each other physically.
- [ ] Players can see each other's movements and emotes.

Reference: 
![image](https://user-images.githubusercontent.com/24496613/213270733-430a3924-2f07-4581-8fb8-b933a4b7d951.png)

ETA: End of the first sprint

**Comment by Lihem** [comment]
This issue is splitted into 2 sub issues.
- #32 
-
