### ISSUE TITLE
Research on Unity Version 

### ISSUE THREAD

**Issue by SelinMergen** [TeamWombat2023/Bil496-Bitirme-Projesi#2]
Epic: #1 

As the scope of this issue, it is expected to be decided which of the unity versions is better for this project.

Expected Unity version must contain some features:

- [ ] Good capability for VR features.
- [ ] Efficient for VR environment.
- [ ] Testing for and without VR must be easily accessible.

Gathered information will be reported in the comment section.

ETA: 1 day

**Comment by cagdasgerede** [comment]
Tüm taskların içerikleri ve beklentiler tanımlanmalı. Ne zaman DONE yapılmış sayılacak tariflenmeli. Görev tanımı açık olmalı. ETA belirtilmeli.

**Comment by kaanefekeles** [comment]
After careful consideration we have decided to use Unity version 2021.3.16f1

We only considered long term support versions and concluded that 2021.3.16f1 includes a range of features that can be useful for our purposes, such as improved VR tools, improved performance and memory management, and new animation features.
