### ISSUE TITLE
Main character walks on keyboard and go up 

### ISSUE THREAD

**Issue by SelinMergen** [TeamWombat2023/Bil496-Bitirme-Projesi#23]
As a solution keyboards label can be change and also there must be a toggle switch to open and close keyboard. Related image for this bug will be added later.
ETA: 2 Days

**Comment by kaanefekeles** [comment]
Unfinished. Keyboard we used is very hard to work with, we will be completely changing it from a drum based keyboard to trigger based keyboard.
