### ISSUE TITLE
Research for specifying library requirements

### ISSUE THREAD

**Issue by MErenB** [TeamWombat2023/Bil496-Bitirme-Projesi#3]
Epic: #1 
Research will be conducted about which SDK's, libraries and standarts will be used for VR development.  
There exists many different frameworks and libraries which we could use for our project. Following technologies will be analysed:

- Virtual Reality Toolkit
- Windows Mixed Reality Toolkit
- Mixed Reality Toolkit
- XR Interaction Toolkit
- Oculus Interaction SDK
- OpenXR Standard

Tests will include the following steps:
- [x] Related documentation for technologies will be inspected for ensuring that it provides the functionality needed.
- [x] A simple demo application will be created for checking the technical usage of the SDK.
- [x] Advantages and disanvantages of SDK's will be listed.
- [x] An SDK will be selected.

The requirements for a suitable SDK:
- Support for numerous VR gesture implementations.
- Seamless Movement or teleportation (locomotion) support with VR handle 
- Accurate aim capabilities
- Accessibility options (Ability to interact with the game with VR handle buttons if needed.)

Issue will be completed when suitable technologies (SDKs, libraries etc.) are selected and listed in a file with their reason of choosing. 

ETA: 4 days

**Comment by cagdasgerede** [comment]
Tüm taskların içerikleri ve beklentiler tanımlanmalı. Ne zaman DONE yapılmış sayılacak tariflenmeli. Görev tanımı açık olmalı. ETA belirtilmeli.

**Comment by MErenB** [comment]
The specified technologies (SDK, library,  standard) are researched. Comparisons are listed in Table1 below.


**Virtual Reality Toolkit (VRTK)**

|                             | Virtual Reality Toolkit (VRTK)  | Windows Mixed Reality Toolkit | Mixed Reality Toolkit | XR Interaction Toolkit                             | Oculus Interaction SDK             |
|-----------------------------|---------------------------------|-------------------------------|-----------------------|----------------------------------------------------|------------------------------------|
| Platform Support            | Various platforms               | Various platforms             | Various platforms     | Various platforms                                  | Only Oculus                        |
| Input Detection             | Device                          | Action                        | Action                | Device & Action                                    | Device                             |
| Examples on the Web         | Documents and community support | Only Documents                | Only Documents        | Documents and rich community support               | Only documents                     |
| Movement  Implementations   | Only Locomotion                 | Only Locomotion               | Only Locomotion       | Locomotion and movement with VR  contoller buttons | Locomotion is outdated             |
| Hand Tracking               | No                              | Yes                           | Yes                   | Yes                                                | Yes                                |
| 2 Hands Based  Interactions | Has samples                     | Has samples                   | Has samples           | Needs to be  implemented                           | Works poorly                       |
| Handling Voice Input        | No                              | No                            | No                    | No                                                 | Has numerous API's for voice input |
| Hand Tracking Support       | No                              | Yes                           | Yes                   | Yes                                                | Yes                                |

Table1: Functionality comparison between popular VR SDK's.

The key points of the Table1 are:
- XR Interaction Toolkit has both Locomotion and movement with VR controller buttons built-in. The simplicity of implementing the movement function will be beneficial for the games that need location change.
- XR Interaction Toolkit has the biggest support among VR SDK's.
- Only Oculus Interaction SDK implements voice handling. Other SDK's need external solutions for it.
- Oculus Interaction SDK has poor platform support. It only supports Oculus.

The SDK that will be selected needs to have enough community support and it needs to have enough functionality to implement VR interactions. Additionally, it needs to support hand tracking as well for detecting rather complex hand movements. 

After considering these criteria, it is decided to examine **XR Interaction Toolkit** and **Oculus Interaction SDK** with simple demo applications. Demos will be created with these SDK's and their capabilities will be further investigated.

This report completes the first item in the issue.

**Comment by MErenB** [comment]
After completing the general research about VR tools, 2 suitable SDKs are further investigated. A simple project is created for **XR Interaction Toolkit** and **Oculus Interaction SDK**. The SDKs are inspected technically.

The following cases are inspected in these demo applications:
-  How is the VR hardware implemented? How to access the VR headset or VR controllers. Is the VR controller for the left hand differs from the other right's?
- How are VR actions implemented? How to accomplish some simple actions such as grabbing, moving, and interacting with objects?


**XR Interaction Toolkit (XRI)**

XRI Interaction Toolkit added to a blank Unity project. Its initialization was simple. Since it can work with multiple platforms, it was not needed to configure numerous options. 

The findings are explained in the following images. 
![Pasted image 20230116224501](https://user-images.githubusercontent.com/78208804/213276729-9b3c8ae8-7fc4-452c-8a63-9bfe20a8ce69.png)
Image 1: Controller preset for Right hand. XRI implements both hands individually. Hands work out-of-the-box. Also, an activity that uses both hands can be implemented easily since they have different functions. This will be helpful in the development of some games.   


![Pasted image 20230116225141](https://user-images.githubusercontent.com/78208804/213276797-c678b2c3-4f15-407a-9860-42081c3ffdad.png)
Image 2: Contents of the XRI SDK. It has a demo scene to test its capabilities and has example code to implement various VR actions such as movement. It also has presets for commonly used VR actions. These include presets for the continuous move, continuous turn, grab move for both hands, and for some other simple actions. These presets can remove the effort of implementing some actions.  

![Pasted image 20230118133943](https://user-images.githubusercontent.com/78208804/213276858-3d9d9ccf-60eb-4eb3-a56a-4a9b7403bdfe.png)
Image 3: Preset for the continuous move. The presets that XRI provides also have flexibility. It can be seen from the image that various parameters can be adjusted for accomplishing needed functionality.


**Oculus Interaction SDK**

Oculus Interaction SDK was added to the blank Unity project. Its initialization was difficult because a lot of adjustments needed to be made to make it compatible with Oculus. These adjustments reduce the flexibility of the project. 
Other findings about the Oculus Interaction SDK are explained in the following images.

![Pasted image 20230118134431](https://user-images.githubusercontent.com/78208804/213276906-ce842501-34cc-4b2c-a0da-7bacc41a0e9e.png)
Image 4: Contents of the Oculus Interaction SDK. Only a small part of its features will be used in our project. Others will unnecessarily increase the project size.

![Pasted image 20230118134900](https://user-images.githubusercontent.com/78208804/213276949-c8f79545-5f36-4936-841a-3643471a1a3f.png)
]]
Image 5: The prefabs provided by Oculus Interaction SDK. It has prefabs for the hands and the VR camera. Runtime Controller and Manager prefabs enforce a common development practice. However, they need to be used properly to run the VR application. 


![Pasted image 20230118134740](https://user-images.githubusercontent.com/78208804/213277031-8e9816b5-bfb0-4713-92b2-1238caea4e1d.png)
Image 6: The prefab for the left hand. It provides some parameters to tweak however it can't be used on its own. 


**Advantages and Disadvantages of  XRI and Oculus Interaction SDK**

Table 1: Advantages and disadvantages of XRI
| Advantages                                         | Disadvantages                                          |
|----------------------------------------------------|--------------------------------------------------------|
| Can work out of the box                            | Some haptic feedbacks needs to be implemented manually |
| Can be tweaked for obtaining desired functionality | Spatial sound needs to be implemented                  |
| Movement functionality is already implemented      |                                                        |
| Has examples in  the SDK                           |                                                        |



Table 2: Advantages and disadvantages of Oculus Interaction SDK
| Advantages                                       | Disadvantages                                                      |
|--------------------------------------------------|--------------------------------------------------------------------|
| Capable for handling complex requirements        | Hard to accomplish simple functionalities                          |
| All hardware features of Oculus 2 is implemented | Movement with VR controller sticks are not implemented             |
| -                                                | Hard to tweak the default setting to obtain the desired behavior |
| -                                                | Most of its features will be a burden in our project.              |



The tables above summarise the pros and cons of both SDKs. XRI provides most of the functionalities we need out of the box. Even though XRI lacks some functionalities, they can be implemented or solved by using other libraries easily. 

Oculus Interaction SDK has all of the hardware features (haptic feedback etc.) implemented however our games will not mainly depend on them. Additionally, needed functionality can be implemented. 
Also, our games need movement capability with the VR controller sticks. Some of the games that will be designed rely on this feature. 



**Conclusion**

After inspecting the XRI and Oculus Interaction SDK technically, it is decided that XRI will be more suitable for our project. Due to its simplicity, we can start the development and testing processes. The functionalities the XRI lacks will be scheduled to be developed as well.
