### ISSUE TITLE
Lobby Scene Interactions

### ISSUE THREAD

**Issue by Lihem** [TeamWombat2023/Bil496-Bitirme-Projesi#32]
Epic: #10 
This is a sub-issue for Design of the Lobby Issue  #18 .

It contains interactions in the lobby such as:

- [x] hand animations
- [x] grabbing, selecting and hovering objects

ETA: End of the first sprint

**Comment by SelinMergen** [comment]
One of the tasks is not completed yet ( Interaction between players ).
