### ISSUE TITLE
Research on which assets to use in our project

### ISSUE THREAD

**Issue by MErenB** [TeamWombat2023/Bil496-Bitirme-Projesi#4]
Epic: #1 
The research will be conducted for finding available assets to use in our minigames. We need assets to use in our games. 

The assets we will select need to meet the following criteria:

- Easy to use
- Free

The assets that are gathered will be used mainly for testing. Therefore their design quality will not be a higher concern.

Following types of assets will be required in our games:

- 3D vehicles: Cars and aircrafts
- Some weapons for our FPS minigame
- Some simple objects such as boxes for testing the VR interactions
- Some terrain textures (Grass, flowers) 
- Some simple environmental assets such as trees   

This task will be completed when all of the required assets listed above are found. They will be documented under the comment section and Github Wiki page of the project.

ETA: 2 to 3 days

**Comment by cagdasgerede** [comment]
Tüm taskların içerikleri ve beklentiler tanımlanmalı. Ne zaman DONE yapılmış sayılacak tariflenmeli. Görev tanımı açık olmalı. ETA belirtilmeli.

**Comment by MErenB** [comment]
Free unity assets are reviewed for finding suitable 3D designs for our games. These assets will be used in the testing stages of our games. Selected assets are listed below.




![Image](https://user-images.githubusercontent.com/78208804/213867705-c6b9ae49-fc59-4fa2-b696-868388415cca.png)

Image 1: A 3D car object. This car asset will be used in our games that require a car.



![Image](https://user-images.githubusercontent.com/78208804/213867804-8a5543dc-419c-4208-a16c-8a264828899a.png)

Image 2: An asset set containing various objects. These will be used in our games to test the VR functionalities.




![Image](https://user-images.githubusercontent.com/78208804/213867929-0ea6e2d1-930c-47fb-b3f8-6536f881700e.png)

Image 3: An asset containing several grass textures. Testing of the VR visuals requires different textures.



![Image](https://user-images.githubusercontent.com/78208804/213868014-f1e7ad06-6df0-4d70-9dbc-1963c46d8038.png)

Image 4: An asset containing different fruits.




![Image](https://user-images.githubusercontent.com/78208804/213868061-0e68d694-7dd3-4a19-b999-bdea13061d74.png)

Image 5: 3D weapons. These will be used in order to test our first-person-shooter (FPS) games. 


**Conclusion**

These assets will be mainly used in the testing stages of our development process. Most of the assets in the games will be designed by us and the remaining assets will be replaced with higher-quality assets rather than these testing assets listed above.
