### ISSUE TITLE
Research about minigames

### ISSUE THREAD

**Issue by MErenB** [TeamWombat2023/Bil496-Bitirme-Projesi#6]
Epic: #1 
Available VR games will be inspected with a scientific point of view to design our minigame. 
Gathered information will be reported under the comment section.
ETA: 3 Days

**Comment by cagdasgerede** [comment]
Tüm taskların içerikleri ve beklentiler tanımlanmalı. Ne zaman DONE yapılmış sayılacak tariflenmeli. Görev tanımı açık olmalı. ETA belirtilmeli.

**Comment by Lihem** [comment]
Minigames should have different mechanics for more rich gaming experience.

Here are some minigame types that has different gaming mechanics. It will not be the exactly same but our minigames will based on these games. 

Fruit ninja:
-A mini game that user can cut dropping objects with a sword.
-In our opinion using a sword in VR environment will be challenging and fun.
![5fa23905123118018f5e286c_3-op](https://user-images.githubusercontent.com/75074894/216597987-4b6710b5-ecb4-44af-8939-2b8c93de7293.jpeg)
