### ISSUE TITLE
Initializing Unity project 

### ISSUE THREAD

**Issue by MErenB** [TeamWombat2023/Bil496-Bitirme-Projesi#9]
Epic: #5 
Unity project will be initialized such that:

- all required SDK's and libraries are included
- Project can be accessed in multiple operating systems. (Linux, Mac, Windows)
- Version specified here will be used: #2 
ETA: 3 day

**Comment by cagdasgerede** [comment]
Tüm taskların içerikleri ve beklentiler tanımlanmalı. Ne zaman DONE yapılmış sayılacak tariflenmeli. Görev tanımı açık olmalı. ETA belirtilmeli.
